---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Apache
      ansible.builtin.apt:
        name: apache2
        state: present
    - name: Start the apache2 services
      ansible.builtin.service:
        name: apache2
        state: started
        enabled: true

    - name: Create uploads folder
      ansible.builtin.file:
        path: /var/www/html/uploads
        state: directory
        owner: root
        group: root
        mode: '0777'

    - name: Copy index.php
      ansible.builtin.copy:
        src: www/index.php
        dest: /var/www/html/index.php

    - name: Copy favicon.ico
      ansible.builtin.copy:
        src: www/favicon.ico
        dest: /var/www/html/favicon.ico

    - name: Copy style.css
      ansible.builtin.copy:
        src: www/style.css
        dest: /var/www/html/style.css

    - name: Copy script.js
      ansible.builtin.copy:
        src: www/scrpt.js
        dest: /var/www/html/script.js

    - name: Copy conn.php
      ansible.builtin.copy:
        src: www/conn.php
        dest: /var/www/html/conn.php

    - name: Copy create_thread.php
      ansible.builtin.copy:
        src: www/create_thread.php
        dest: /var/www/html/create_thread.php

    - name: Copy view_forum.php
      ansible.builtin.copy:
        src: www/view_forum.php
        dest: /var/www/html/view_forum.php

    - name: Copy view_thread.php
      ansible.builtin.copy:
        src: www/view_thread.php
        dest: /var/www/html/view_thread.php

    - name: Install MariaDB server
      ansible.builtin.apt:
        name: mariadb-server
        state: present

    - name: Start and enable MariaDB service
      ansible.builtin.service:
        name: mariadb
        state: started
        enabled: true

    - name: Ensure pip is installed
      ansible.builtin.apt:
        name: python3-pip
        state: present

    - name: Install PyMySQL
      ansible.builtin.pip:
        name: PyMySQL
        state: present

    - name: Create .my.cnf for MySQL authentication
      ansible.builtin.copy:
        dest: "~/.my.cnf"
        content: |
          [client]
          user=kjak_user
          password=kjak2kjak
        mode: '0600'
      become: yes

    - name: Set root password for MySQL/MariaDB
      ansible.builtin.mysql_user:
        name: kjak_user
        password: kjak2kjak
        login_user: root
        check_implicit_admin: yes
        host_all: yes
      become: yes

    - name: Ensure the database 'kjakdb' exists
      ansible.builtin.mysql_db:
        name: kjakdb
        state: present
        login_user: kjak_user
        login_password: kjak2kjak

    - name: Ensure the kjakdb user exists with privileges
      ansible.builtin.mysql_user:
        name: kjak_user
        password: kjak2kjak
        priv: 'kjakdb.*:ALL'
        state: present
      become: yes

    - name: Copy SQL script to target machine
      ansible.builtin.copy:
        src: sql/kjakdb.sql
        dest: /tmp/kjakdb.sql

    - name: Import SQL script into kjakdb database
      ansible.builtin.mysql_db:
        name: kjakdb
        state: import
        target: /tmp/kjakdb.sql
      become: yes

    - name: Copy check and update script on kjakdb
      ansible.builtin.copy:
        src: sh/update_kjakdb.sh
        dest: /tmp/update_kjakdb.sh
        mode: '0755'

    - name: Execute the update script on kjakdb
      ansible.builtin.command:
        cmd: /tmp/update_kjakdb.sh
